version: '3.1'

services:
  app:
    build: .
    command: npm run build
    environment:
      NODE_ENV: production
    ports:
      - '3000:3000'
    volumes:
      - .:/home/app/appDir:cached
      - /home/app/appDir/node_modules
    networks:
      - backend

  postgres-dev:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-dev:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 1s
      retries: 600

  postgres-stage:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-stage:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 1s
      retries: 600

networks:
  backend:
    name: app

volumes:
  postgres-dev:
  postgres-stage:

